version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "topic1:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  studentDB:
    image: postgres:13.3
    container_name: studentDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student

  elk:
    image: sebp/elk:8.11.1
    ports:
      - ${ELK_KIBANA_UI_HOST_PORT:-5601}:5601
      - ${ELK_ELASTIC_JSON_HOST_PORT:-9200}:9200
      - ${ELK_LOGSTASH_HOST_PORT:-5044}:5044
      - ${ELK_LOGSTASH_INPUT_HOST_PORT:-5030}:5030
    env_file: ./elk.env
    volumes:
      - ${ELK_KIBANA_CONFIG_VOLUME}:/kibana.yml
      - ${ELK_LOGSTASH_SERVICES_CONFIG_VOLUMES}:/logstash.conf